export const GET_INVENTORY = 'GET_INVENTORY';
export const SET_LOADING = 'SET_LOADING';
export const SET_CURRENT = 'SET_CURRENT';
export const LOGS_ERROR = 'LOGS_ERROR';
export const ADD_INVENTORY = 'ADD_INVENTORY';
export const DELETE_INVENTORY = 'DELETE_INVENTORY';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';